/* Generated by cleverdump.
   Image: /var/mobile/Applications/27F3A053-62AE-470D-90AB-7AADC0E84F65/TheWorld.app/TheWorld
 */

@class UnderView, LoadView;

@interface StackBaseVC : UIViewController  {
    BOOL isFrame;
    BOOL isGesture;
    LoadView *_load;
    UnderView *_under;
}

@property BOOL isFrame;
@property BOOL isGesture;


- (BOOL)isGesture;
- (void)removeView;
- (void)setIsFrame:(BOOL)arg1;
- (BOOL)isFrame;
- (void)viewDidLoad;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)startLoading;
- (void)setIsGesture:(BOOL)arg1;
- (void)naviHome:(id)arg1;
- (void)naviBack:(id)arg1;
- (float)outAnimation:(float)arg1;
- (void)stopIntraction;
- (float)inAnimation:(float)arg1;
- (void)endLoading;
- (void)makeView;
- (void)changeHeight;

@end
