/* Generated by cleverdump.
   Image: /var/mobile/Applications/27F3A053-62AE-470D-90AB-7AADC0E84F65/TheWorld.app/TheWorld
 */

@class NSString, UIWebView;

@interface WebVC : StackBaseVC <UIWebViewDelegate,UIActionSheetDelegate> {
    NSString *url;
    UIWebView *_web;
}

@property(retain) NSString * url;

- (void)setUrl:(NSString*)arg1;
- (id)url;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
- (void)viewDidLoad;
- (id)init;
- (void)naviReload:(id)arg1;
- (void)setDicStatus;
- (void)naviSendto:(id)arg1;
- (void)naviStop:(id)arg1;
- (void)naviForward:(id)arg1;
- (void)naviReturn:(id)arg1;
- (float)outAnimation:(float)arg1;
- (float)inAnimation:(float)arg1;
- (void)makeView;
- (void)changeHeight;
- (void)findTextViewAndMoveToTop:(UIView *)v;

@end
